### ISSUE TITLE
Provide Kotlin support

### ISSUE THREAD

**Issue by roschlau** [anupcowkur/here-be-dragons#2]
This is a neat little plugin, I can see it come in very helpful. I mainly develop in Kotlin though, so it would be great if I could also use it there - right now, I can annotate Kotlin code and it will show the dragon when called from Java code, but no dragons are shown in Kotlin code.

**Comment by anupcowkur** [comment]
Have this planned for a future update

**Comment by anupcowkur** [comment]
Not sure how to go about achieving this. Any guidance that would point me in the right direction appreciated. A PR would be even better 😄
