### ISSUE TITLE
Ability to mark all methods inside a type with SideEffect

### ISSUE THREAD

**Issue by rjoncontract** [anupcowkur/here-be-dragons#6]
For instance, all methods in a Retrofit interface instance carry side-effects. Instead of marking every single method with a `@SideEffect` (which also clutters the method definitions in the class), I prefer marking the entire type instead.

This would also require another annotation to mark exclusions inside a class. Maybe another annotation named `@Pure`.

**Comment by anupcowkur** [comment]
Let me think about this for a bit. I'll keep the issue open for now.

**Comment by anupcowkur** [comment]
This sounds like a good idea. Don't have time to pick this up right now. PRs welcome though.
