### ISSUE TITLE
Watch for global variable mutation

### ISSUE THREAD

**Issue by vgonda** [anupcowkur/here-be-dragons#7]
Would it be possible to detect side effects in addition to the annotation? Watching for interaction with anything with a greater scope than the method (such as a field). I would be much more likely to use this if I didn't have to remember to add the annotation to every method with a side effect.

**Comment by anupcowkur** [comment]
That's certainly an interesting idea. I'll look into it when I have some time. If you run into something that might shed some light on this, feel free to share or raise a PR.
