### ISSUE TITLE
Annotations for indicating a parameter is modified by the function

### ISSUE THREAD

**Issue by JLLeitschuh** [anupcowkur/here-be-dragons#8]
Let me start by saying, the name you've come up with for this library is awesome, I'm very tempted to steal it to make my own variation.
That being said, I figured I'd run my proposal by you before performing grand theft (please understand this is meant as a compliment, not a threat).

I'd like to be able to annotate the parameters on methods if the parameters get side effected.
For example:

```java
/**
 * Allow us to annotate that collection passed has elements added/removed/sorted/ect...
 * within the method.
 */
int doActions(@SideEffectModifies(type = COLLECTION) final Set<Something> somethings) {
    somethings.add(anotherSomething());
    return somethings.size();
}
```

```java
/**
 * Allow us to annotate that collection elements get modified when passed to the method.
 */
int doActions(@SideEffectModifies(type = ELEMENTS) final Set<Something> somethings) {
    something.forEach(something -> something.setIt("it"));
    return somethings.size();
}
```

```java
/**
 * Allow us to annotate that both kinds of side effecting happens.
 */
int doActions(@SideEffectModifies(type = BOTH) final Set<Something> somethings) {
    somethings.add(anotherSomething());
    something.forEach(something -> something.setIt("it"));
    return somethings.size();
}
```

My particular use case is that I'm refactoring a large swath of code. I'd like myself and other developers to leave hints to each other that we have discovered this kind of side effecting behaviour. The goal is, while you might not be able to do the refactor to fix the problem at the time, you've figured out this is what is going on.

**Comment by anupcowkur** [comment]
Nice idea. Not sure about the multiple types of the annotation though. Perhaps a single `@SideEffectModifies` annotation to hint that param is going to be mutated?

example:
```
int doActions(@SideEffectModifies final Set<Something> somethings) {
    somethings.add(anotherSomething());
    something.forEach(something -> something.setIt("it"));
    return somethings.size();
}
```

**Comment by JLLeitschuh** [comment]
Personally, I'd rather be able to flag the two different kinds independently because each has different characteristics and fixes. For example, if the collection is side effected, you can't pass an immutable collection into the method (like guava's `ImmutableSet`) but if the elements are side effected you can still pass an immutable collection without having the code not work correctly. Would two different annotations be better instead?

**Comment by anupcowkur** [comment]
>For example, if the collection is side effected, you can't pass an immutable collection into the method (like guava's ImmutableSet) but if the elements are side effected you can still pass an immutable collection without having the code not work correctly

 I think you're talking about `Unmodifiable` collections which means you can't add or remove elements but the underlying collection can change. It's like a read only wrapper.

`Immutable` means that no additions, deletions or *modifications* are allowed.

 As someone reading code, if I see an annotation that says the collection I'm passing in is going to change in some way, I'm gonna be careful with it. A single annotation to hint this should suffice I think.

**Comment by roschlau** [comment]
> Immutable means that no additions, deletions or modifications are allowed.

Guava's `ImmutableX` Collections don't work that way, though - there is simply no way they could enforce immutability on the contained items as well.

**Comment by JLLeitschuh** [comment]
There is a difference between immutable data types and deeply immutability data types.
